# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GooglePlacesAPI-DEMO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GooglePlacesAPI-DEMO
#pod 'GooglePlaces'
#pod 'GooglePlacePicker'
#pod 'GoogleMaps'

  target 'GooglePlacesAPI-DEMOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GooglePlacesAPI-DEMOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
